### ISSUE TITLE
NPM package: Error when trying to launch agnai after updating

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#184]
This error pops up after running `npm install agnai -g`, then running `agnai`

```
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\agnai\dist\assets'
    at readdirSync (node:fs:1444:3)
    at getFolders (C:\Users\Administrator\AppData\Roaming\npm\node_modules\agnai\srv\bin.js:121:39)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\agnai\srv\bin.js:32:17)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\agnai\\dist\\assets'
}
```

**Comment by ghost** [comment]
The manual workaround is simply creating an assets folder inside node_modules/agnai/dist/

**Comment by sceuick** [comment]
Thanks, will fix.

**Comment by sceuick** [comment]
Should now be fixed in `alpha-15`.
