### ISSUE TITLE
Problem with character generator on 3rd party setup

### ISSUE THREAD

**Issue by cingorn** [agnaistic/agnai#771]
**Describe the bug**
Trying to generate a character using a 3rd party preset results in an error:
```
[api] [2023-12-19T21:00:14Z] ERROR (app/18532): Error occurred handling request
[api]     requestId: "5354f06f-4809-4552-a031-68f0dd241072"
[api]     url: "/api/chat/guidance"
[api]     method: "POST"
[api]     user: "admin"
[api]     err: {
[api]       "type": "Error",
[api]       "message": "Textgen request failed: AggregateError",
```

**To Reproduce**
1. Create any 3rd Party preset, make sure it's working by chatting with a character.
2. Select the same model for character generator and click Generate.

**Expected behavior**
Character generator works with 3rd Party preset

**Additional context**
There seems to be some kind of a problem with the URL passed to the generator, this line:
https://github.com/cingorn/agnai/blob/dev/srv/adapter/ooba.ts#L18
results in the URL being empty.

**Comment by sceuick** [comment]
Are there any logs from ooba?

**Comment by LukePavelka** [comment]
```
[2024-03-17T22:45:55Z] ERROR (app/22): Error occurred handling request
    requestId: "f997bba9-f4a9-4009-b198-3b658e89e498"
    url: "/api/chat/guidance"
    method: "POST"
    user: "arwwarr"
    err: {
      "type": "Error",
      "message": "Textgen request failed: AggregateError",
      "stack":
          Error: Textgen request failed: AggregateError
              at inferenceAsync (/app/srv/adapter/generate.js:65:27)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async infer (/app/srv/adapter/generate.js:91:27)
              at async runGuidance (/app/common/guidance/guidance-parser.js:48:33)
              at async guidanceAsync (/app/srv/adapter/generate.js:116:20)
              at async /app/srv/api/chat/inference.js:157:20
              at async wrapped (/app/srv/api/wrap.js:12:28)
    }
```
